 services:
  - type: web
    name: calendar-reminder-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    region: oregon  # or frankfurt, singapore, etc.
    plan: free
